spring.application.name=demo
# Database filename
spring.datasource.url=jdbc:sqlite:uniguard.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update